# Generated by Django 3.1.7 on 2021-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
